### ISSUE TITLE
Email validation post requests are not sent 

### ISSUE THREAD

**Issue by lucas2005gao** [UoaWDCC/ASPA-EnrollmentForm#33]
Upon on submitting email validation request more than once, the request doesn't seem to be sent

**Comment by lucas2005gao** [comment]
Leaving the email section empty -> press okay, the first request processes fine, the second one seem to not work

**Comment by Ray-F** [comment]
This is intended functionality. We won’t send duplicate calls to Gsheet API (to reduce number of requests) if neither email or name has changed. Could be worth keeping the previous red message on for the whole time instead of the misleading “loading” icon when the enter key is pressed again.

**Comment by lucas2005gao** [comment]
Uh okay I see, then I guess its just a change on the front end. 
How do you keep track of if the email is changed or not?

**Comment by Ray-F** [comment]
Line 178 of `enrollmentForm.js`, view Martin’s most recent PR and you will see the specific changes there.

**Comment by lucas2005gao** [comment]
Uh I see! Cool!

I guess we will just need to show the user sort of UI response when they try to submit same name+email.
(make an `else` statement for the `if` statement on line 191 `enrollmentForm.js` perhaps)
