### ISSUE TITLE
[FEATURE] Make "sign up to ASPA" a permanent link on login

### ISSUE THREAD

**Issue by VillaramaEnzo** [UoaWDCC/ASPA-EnrollmentForm#56]
**Is your feature request related to a problem? Please describe.**
If a person wants to sign-in on the day, but is not a registered member. Need the ability to add him to the membership list

**Describe the solution you'd like**
Maybe just clickable text that sends them to our signup form?
The goal is to make the email recognised by the system. So I think this is the easiest way. 
As when they do fill out the form, their details should automatically be added to the google sheet. As such from my understanding, because their details have just been added, if they go back to the sign in form and try to submit again, they should be able to continue from where they left off. i.e from the point of the screenshot you've added to the group chat, showing an unrecognised email

**Describe alternatives you've considered**

**Additional context**

**Comment by Ray-F** [comment]
Add "sign up" link (pointing to Google Form) permanently on the "user/email" page.

Change response text to direct to the link below.
