### ISSUE TITLE
[FEATURE] Better view when we not accepting the registation 

### ISSUE THREAD

**Issue by jameszu** [UoaWDCC/ASPA-EnrollmentForm#74]
**Is your feature request related to a problem? Please describe.**
Current;y when the form is disabled, there is one simple line on the page, need a better UI for that

**Describe the solution you'd like**
Keep the original home page but disable button and add more info say like full registration bla on the page. 

**Describe alternatives you've considered**
None for now

**Additional context**
<img src="https://user-images.githubusercontent.com/41566813/112411572-00959500-8d82-11eb-9330-25359fe253ca.png" width="500px" />

**Comment by Ray-F** [comment]
Change the text to:

"Sign up is not open yet"

Some image (?) – @VillaramaEnzo

with consistent colouring
